### ISSUE TITLE
Modify how /data/ and /output/ appear in gitignore

### ISSUE THREAD

**Issue by JakeKea** [ncl-icb-analytics/ncl_project#3]
Suggestion to change .gitignore to use:

```
# Exclude the following directories 
/data/*
/output/*
```
Instead of without the * so empty versions of the folders appear in the repo without having to force add them.
Aware some environments may treat /data/ the same as /data/* but at least on my machine and environment, my repos will not include the data or output folder.

Reasons for change:
- Having the data folder appear when cloning repos that require data files to be added to it is more clear than requiring users who clone the repos to make the data folder themselves.
- For code that outputs something into the output folder, the code might assume the output folder already exists and fail if the user cloning the repo doesn't create the output folder ahead of running the repo code.

**Comment by chrismainey** [comment]
Solved by #2

**Comment by chrismainey** [comment]
Incorrectly closed
